config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :create, :new] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: {scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_one_attached :photo
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(strong_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  def strong_params
    params.require(:bookmark).permit(:comment, :movie_id, :photo)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(strong_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def strong_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class=container>
  <h2>New Bookmark</h2>
    <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Add Movie to List", class: "btn btn-primary"%>
    <% end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class=container>
  <h2>All Movielists</h2>
    <ul class="list-group">
      <% @lists.each do |list| %>
        <li class="list-group-item">
        <% if list.photo.attached? %>
        <%=  cl_image_tag(list.photo.key, height: 150, width: 150, crop: :fill)  %>
        <% end %></li>
        <li><%= link_to list.name, list_path(list)%></li>
      <% end %>
    </ul>

    <div class=container>
      <%= link_to "Add new List", new_list_path(@list) %>
    </div>

</div>

app/views/lists/new.html.erb
<div class=container>
<h3>Add new List</h3>
<%= simple_form_for [ @bookmark, @list ] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Enter Listname", class: "btn btn-primary" %>
<% end %>
</div>
<div class=container>
  <%= link_to "Homescreen", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h2> <%= @list.name %></h2>
    <% if @list.photo.attached? %>
    <p><%=  cl_image_tag(@list.photo.key, height: 250, width: 250, crop: :fill)  %><p>
    <% end  %>
      <p><% @list.movies.each do |movie| %><p>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie)  %>
        <%=movie.title  %>
        <div class="container">
        <%= link_to "Delete Bookmark", bookmark_path(bookmark), method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
      <%end  %>
</div>
<div class="container">
  <%= link_to "Homescreen", lists_path %>
</div>
<div class="container">
      <%= link_to "Add new Bookmark", new_list_bookmark_path(@list) %>
</div>